package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextPane;

/**
 * Window containing information about the product.
 * 
 * @author Nick Spokes
 * @version 1
 * 
 *          This work complies with the JMU Honor Code.
 */
public class AboutWindow extends JFrame implements ActionListener
{
  private static final long serialVersionUID = 1L;
  private static final String CONFIRM = UnitEDWindow.STRINGS.getString("CONFIRM");
  private static final String FULL = UnitEDWindow.STRINGS.getString("FULL");
  private static final String ABOUT = UnitEDWindow.STRINGS.getString("ABOUT");
  private static final String PRODUCT_AND_COMPANY_NAME = 
      UnitEDWindow.STRINGS.getString("PRODUCT_AND_" + "COMPANY_NAME");

  /**
   * Constructs an AboutWindow object.
   * 
   * @param icon - Icon to use for the software
   */
  public AboutWindow(final Image icon)
  {
    super();
    super.setBounds(100, 100, 420, 300);
    super.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    super.getContentPane().setLayout(new BorderLayout(0, 0));
    super.setTitle(ABOUT);
    super.setIconImage(icon);
    super.setResizable(false);
    super.setAlwaysOnTop(true);
    initializeWindow();
    super.setVisible(true);
  }
  
  /**
   * Initializes the window.
   */
  private void initializeWindow()
  {
    // Logo panel
    JPanel logoPnl = new JPanel();
    super.getContentPane().add(logoPnl, BorderLayout.NORTH);
    logoPnl.setLayout(new BoxLayout(logoPnl, BoxLayout.X_AXIS));
    logoPnl.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
    
    // UnitED logo
    URL url = this.getClass().getResource("/customization/logo.png");
    ImageIcon ico = new ImageIcon(url);
    JLabel logo = new JLabel(ico);
    logoPnl.add(logo);
    logo.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
    
    // Name of the product and company
    JLabel name = new JLabel(PRODUCT_AND_COMPANY_NAME);
    name.setFont(new Font("Tahoma", Font.PLAIN, 20));
    logoPnl.add(name);
    name.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 5));
    
    // Main panel
    JPanel mainPnl = new JPanel();
    super.getContentPane().add(mainPnl, BorderLayout.CENTER);
    mainPnl.setLayout(new GridLayout(0, 1, 0, 0));
    
    // Information pane
    JTextPane info = new JTextPane();
    mainPnl.add(info);
    info.setEditable(false);
    info.setText(FULL);
    
    // Button panel
    JPanel btnPnl = new JPanel();
    super.getContentPane().add(btnPnl, BorderLayout.SOUTH);
    
    // Confirm button
    JButton confirmBtn = new JButton(CONFIRM);
    btnPnl.add(confirmBtn);
    confirmBtn.addActionListener(this);
  }

  /**
   * Handles the ActionEvents generating by the user pressing the confirm button.
   * 
   * @param e - The ActionEvent generated by the user pressing the confirm button
   */
  @Override
  public void actionPerformed(final ActionEvent e)
  {
    String command = e.getActionCommand();
    if (command.equals(CONFIRM))
    {
      super.dispose();
    }
  }
}
